/**
 * Runs Pi's native compaction on a dedicated model (for example a cheap Haiku).
 *
 * Copied from pi-compaction-model 0.1.0 by JMHSV (MIT, see LICENSE):
 * https://github.com/JMHSV/pi-compaction-model
 * Configure with `compactionModel` in ~/.pi/agent/settings.json.
 * Falls back to the session model when the chosen one is missing or fails.
 */
import {
  compact,
  type ExtensionAPI,
} from "@earendil-works/pi-coding-agent";
import { loadConfig, parseModelReference } from "./config.js";
import { ENTRY_TYPE, reportParts, runningParts, type CardStyle, type CompactionReport } from "./report.js";
import { ExpandedCard, WidthAwareLines } from "../tool-presentation/tidy/cards/card.js";
import { loadTidyExpandedMaxLines, loadTidyIcons, loadTidyMode } from "../tool-presentation/tidy/config.js";

const STATUS_KEY = "compaction-model";

// Kept for headless runs; the TUI shows a transcript line and a notice instead.
function warn(message: string, error?: unknown): void {
  if (process.stdout.isTTY) return;
  if (error === undefined) console.warn(`[pi-compaction-model] ${message}`);
  else console.warn(`[pi-compaction-model] ${message}`, error);
}

/**
 * Hook-provided compactions are marked as extension-generated by Pi. Native
 * preparation intentionally does not trust arbitrary extension details, so it
 * will not carry their file lists into a later compaction. Since this extension
 * returns Pi's own details shape, restore those lists before calling native
 * compact() again. Sets make this harmless for native previous entries too.
 */
function restorePreviousFileOperations(
  preparation: {
    fileOps: { read: Set<string>; edited: Set<string> };
  },
  branchEntries: Array<{ type: string; details?: unknown }>,
): void {
  const previous = [...branchEntries].reverse().find((entry) => entry.type === "compaction");
  if (!previous || typeof previous.details !== "object" || previous.details === null) return;

  const details = previous.details as {
    readFiles?: unknown;
    modifiedFiles?: unknown;
  };

  if (Array.isArray(details.readFiles)) {
    for (const path of details.readFiles) {
      if (typeof path === "string") preparation.fileOps.read.add(path);
    }
  }

  if (Array.isArray(details.modifiedFiles)) {
    for (const path of details.modifiedFiles) {
      if (typeof path === "string") preparation.fileOps.edited.add(path);
    }
  }
}

type Report = CompactionReport;

export default function compactionModel(pi: ExtensionAPI): void {
  // One compaction runs at a time per session; this carries the hook's outcome to the result events.
  let pending: Report | undefined;
  // Read tidy's settings per render, so /tidy icons, mode and lines apply at once.
  const style = (expanded = false): CardStyle => ({ expanded, icons: loadTidyIcons(), mode: loadTidyMode() });

  pi.registerEntryRenderer<Report>(ENTRY_TYPE, (entry, options, theme) => {
    const report = entry.data;
    if (!report) return undefined;
    const background = (text: string) => theme.bg(report.kind === "used" ? "toolSuccessBg" : "toolErrorBg", text);
    return new ExpandedCard(() => reportParts(report, style(options.expanded)), background, loadTidyExpandedMaxLines);
  });

  const record = (report: Report) => pi.appendEntry<Report>(ENTRY_TYPE, report);

  pi.on("session_before_compact", async (event, ctx) => {
    pending = undefined;
    const config = loadConfig(ctx);
    if (!config || !config.reasons.includes(event.reason)) return;
    const sessionModel = ctx.model ? ctx.model.name || ctx.model.id : undefined;
    const fallback = (why: string, error?: unknown) => {
      warn(`${why}. Using Pi's active model.`, error);
      pending = { kind: "fallback", model: config.model, reason: event.reason, sessionModel, why };
    };

    const reference = parseModelReference(config.model);
    if (!reference) return fallback(`invalid model '${config.model}', expected provider/model`);

    const model = ctx.modelRegistry.find(reference.provider, reference.modelId);
    if (!model) return fallback(`model not found: ${config.model}`);

    const name = model.name || model.id;
    const started = Date.now();
    const running = { name, reason: event.reason, tokensBefore: event.preparation.tokensBefore ?? 0 };
    if (ctx.hasUI) {
      ctx.ui.setStatus(STATUS_KEY, `compacting with ${name}…`);
      ctx.ui.setWidget(STATUS_KEY, (tui, theme) => {
        const timer = setInterval(() => tui.requestRender(), 1000);
        const card = new WidthAwareLines(() => {
          const { head } = runningParts({ ...running, elapsedMs: Date.now() - started }, style());
          return head;
        }, (text) => theme.bg("toolPendingBg", text));
        return Object.assign(card, { dispose: () => clearInterval(timer) });
      });
    }
    try {
      const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
      if (!auth.ok) return fallback(`auth failed for ${config.model}: ${"error" in auth ? auth.error : "unknown error"}`);

      restorePreviousFileOperations(event.preparation, event.branchEntries);

      const result = await compact(
        event.preparation,
        model,
        auth.apiKey,
        auth.headers,
        event.customInstructions,
        event.signal,
        config.thinkingLevel,
        undefined,
        auth.env,
      );
      const elapsedMs = Date.now() - started;
      const usage = result.usage;
      pending = {
        kind: "used",
        model: config.model,
        name,
        reason: event.reason,
        sessionModel,
        tokensBefore: result.tokensBefore,
        keepRecentTokens: event.preparation.settings?.keepRecentTokens,
        summaryTokens: usage?.output,
        inputTokens: usage ? usage.input + usage.cacheRead + usage.cacheWrite : undefined,
        elapsedMs,
      };
      // Stored with the compaction entry, so old sessions show which model wrote each summary.
      const details = { ...(result.details as object | undefined), compactedBy: config.model, compactionMs: elapsedMs };
      return { compaction: { ...result, details } };
    } catch (error) {
      if (event.signal.aborted) return;
      return fallback(`${name} failed: ${error instanceof Error ? error.message : String(error)}`, error);
    } finally {
      if (ctx.hasUI) {
        ctx.ui.setStatus(STATUS_KEY, undefined);
        ctx.ui.setWidget(STATUS_KEY, undefined);
      }
    }
  });

  pi.on("session_compact", async (event, ctx) => {
    const report = pending;
    pending = undefined;
    if (!report) return;
    // A later extension may have replaced our summary; only claim the ones we wrote.
    if (report.kind === "used" && !event.fromExtension) return;
    record(report);
    if (report.kind === "fallback" && ctx.hasUI) ctx.ui.notify(`Compaction fell back to the session model: ${report.why}`, "warning");
  });

  pi.on("session_compact_failed", async (event) => {
    const report = pending;
    pending = undefined;
    if (!report || event.aborted) return;
    record({ kind: "failed", model: report.model, reason: event.reason, sessionModel: report.sessionModel, why: event.errorMessage ?? "unknown error" });
  });

  pi.registerCommand("compact-model", {
    description: "Show which model runs compaction and whether it is ready",
    handler: async (_args, ctx) => {
      const config = loadConfig(ctx);
      if (!config) { ctx.ui.notify("Compaction uses the session model (no compactionModel setting).", "info"); return; }
      const reference = parseModelReference(config.model);
      const model = reference ? ctx.modelRegistry.find(reference.provider, reference.modelId) : undefined;
      if (!model) { ctx.ui.notify(`Compaction model ${config.model} is not available; Pi will use the session model.`, "warning"); return; }
      const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
      const ready = auth.ok ? "ready" : `auth failed: ${"error" in auth ? auth.error : "unknown error"}`;
      ctx.ui.notify(`Compaction model: ${config.model} (${model.name || model.id}) · ${ready} · reasons: ${config.reasons.join(", ")}`, auth.ok ? "info" : "warning");
    },
  });
}

export {
  COMPACTION_REASONS,
  THINKING_LEVELS,
  parseModelReference,
  resolveConfig,
  type CompactionModelConfig,
  type CompactionReason,
  type ThinkingLevel,
} from "./config.js";
export { ENTRY_TYPE, reportParts, reportRows, type CompactionReport } from "./report.js";
