/**
 * Runs Pi's native compaction on a dedicated model (for example a cheap Haiku).
 *
 * Copied from pi-compaction-model 0.1.0 by JMHSV (MIT, see LICENSE):
 * https://github.com/JMHSV/pi-compaction-model
 * Configure with `compactionModel` in ~/.pi/agent/settings.json.
 * Falls back to the session model when the chosen one is missing or fails.
 */
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  compact,
  getAgentDir,
  type ExtensionAPI,
  type ExtensionContext,
} from "@earendil-works/pi-coding-agent";
import { loadConfig, parseModelReference } from "./config.js";
import { decorateSummary, EXTRA_INSTRUCTIONS, firstUserText, mergeInstructions, overThreshold, stripAdditions, summaryReserveTokens } from "./policy.js";
import { ENTRY_TYPE, reportParts, runningParts, type CardStyle, type CompactionReport } from "./report.js";
import { ExpandedCard, WidthAwareLines } from "../tool-presentation/tidy/cards/card.js";
import { loadTidyExpandedMaxLines, loadTidyIcons, loadTidyMode } from "../tool-presentation/tidy/config.js";

const STATUS_KEY = "compaction-model";
// Set in the detached exit-compaction process, so it never spawns another one.
const EXIT_CHILD = process.env.PI_COMPACT_ON_EXIT_CHILD === "1";
const EXIT_RUNNER = fileURLToPath(new URL("./exit-compact.mjs", import.meta.url));

// Kept for headless runs; the TUI shows a transcript line and a notice instead.
function warn(message: string, error?: unknown): void {
  if (process.stdout.isTTY) return;
  if (error === undefined) console.warn(`[pi-compaction-model] ${message}`);
  else console.warn(`[pi-compaction-model] ${message}`, error);
}

/**
 * Hook-provided compactions are marked as extension-generated by Pi. Native
 * preparation intentionally does not trust arbitrary extension details, so it
 * will not carry their file lists into a later compaction. Since this extension
 * returns Pi's own details shape, restore those lists before calling native
 * compact() again. Sets make this harmless for native previous entries too.
 */
function restorePreviousFileOperations(
  preparation: {
    fileOps: { read: Set<string>; edited: Set<string> };
  },
  branchEntries: Array<{ type: string; details?: unknown }>,
): void {
  const previous = [...branchEntries].reverse().find((entry) => entry.type === "compaction");
  if (!previous || typeof previous.details !== "object" || previous.details === null) return;

  const details = previous.details as {
    readFiles?: unknown;
    modifiedFiles?: unknown;
  };

  if (Array.isArray(details.readFiles)) {
    for (const path of details.readFiles) {
      if (typeof path === "string") preparation.fileOps.read.add(path);
    }
  }

  if (Array.isArray(details.modifiedFiles)) {
    for (const path of details.modifiedFiles) {
      if (typeof path === "string") preparation.fileOps.edited.add(path);
    }
  }
}

type Report = CompactionReport;

export default function compactionModel(pi: ExtensionAPI): void {
  // One compaction runs at a time per session; this carries the hook's outcome to the result events.
  let pending: Report | undefined;
  // True while a compaction we started for thresholdPercent is running.
  let thresholdRun = false;
  // Read tidy's settings per render, so /tidy icons, mode and lines apply at once.
  const style = (expanded = false): CardStyle => ({ expanded, icons: loadTidyIcons(), mode: loadTidyMode() });

  pi.registerEntryRenderer<Report>(ENTRY_TYPE, (entry, options, theme) => {
    const report = entry.data;
    if (!report) return undefined;
    const background = (text: string) => theme.bg(report.kind === "used" ? "toolSuccessBg" : "toolErrorBg", text);
    return new ExpandedCard(() => reportParts(report, style(options.expanded)), background, loadTidyExpandedMaxLines);
  });

  const record = (report: Report) => pi.appendEntry<Report>(ENTRY_TYPE, report);

  pi.on("session_before_compact", async (event, ctx) => {
    pending = undefined;
    const config = loadConfig(ctx);
    const reason = thresholdRun ? "threshold" : event.reason;
    if (!config || !config.reasons.includes(reason)) return;
    const sessionModel = ctx.model ? ctx.model.name || ctx.model.id : undefined;
    const fallback = (why: string, error?: unknown) => {
      warn(`${why}. Using Pi's active model.`, error);
      pending = { kind: "fallback", model: config.model, reason, sessionModel, why };
    };

    const reference = parseModelReference(config.model);
    if (!reference) return fallback(`invalid model '${config.model}', expected provider/model`);

    const model = ctx.modelRegistry.find(reference.provider, reference.modelId);
    if (!model) return fallback(`model not found: ${config.model}`);

    const name = model.name || model.id;
    const started = Date.now();
    const running = { name, reason, tokensBefore: event.preparation.tokensBefore ?? 0 };
    if (ctx.hasUI) {
      ctx.ui.setStatus(STATUS_KEY, `compacting with ${name}…`);
      ctx.ui.setWidget(STATUS_KEY, (tui, theme) => {
        const timer = setInterval(() => tui.requestRender(), 1000);
        const card = new WidthAwareLines(() => {
          const { head } = runningParts({ ...running, elapsedMs: Date.now() - started }, style());
          return head;
        }, (text) => theme.bg("toolPendingBg", text));
        return Object.assign(card, { dispose: () => clearInterval(timer) });
      });
    }
    try {
      const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
      if (!auth.ok) return fallback(`auth failed for ${config.model}: ${"error" in auth ? auth.error : "unknown error"}`);

      restorePreviousFileOperations(event.preparation, event.branchEntries);
      // Our blocks are re-added below; keep them out of the model's input.
      if (event.preparation.previousSummary) event.preparation.previousSummary = stripAdditions(event.preparation.previousSummary);

      // Pi caps the summary at 0.8 × reserveTokens (about 13K). Haiku's long summaries hit that cap and fall back.
      const preparation = { ...event.preparation, settings: { ...event.preparation.settings, reserveTokens: summaryReserveTokens(event.preparation.settings?.reserveTokens, config.summaryMaxTokens) } };
      const result = await compact(
        preparation,
        model,
        auth.apiKey,
        auth.headers,
        mergeInstructions(EXTRA_INSTRUCTIONS, event.customInstructions),
        event.signal,
        config.thinkingLevel,
        // Without this, compact() only sees pi-ai's built-in providers, so models
        // from extension providers such as claude-code fail with "No API provider".
        (streamModel, context, options) => ctx.modelRegistry.streamSimple(streamModel, context as never, options),
        auth.env,
      );
      const elapsedMs = Date.now() - started;
      const usage = result.usage;
      pending = {
        kind: "used",
        model: config.model,
        name,
        reason,
        sessionModel,
        tokensBefore: result.tokensBefore,
        keepRecentTokens: event.preparation.settings?.keepRecentTokens,
        summaryTokens: usage?.output,
        inputTokens: usage ? usage.input + usage.cacheRead + usage.cacheWrite : undefined,
        elapsedMs,
      };
      // Stored with the compaction entry, so old sessions show which model wrote each summary.
      const details = { ...(result.details as object | undefined), compactedBy: config.model, compactionMs: elapsedMs };
      const summary = decorateSummary(result.summary, firstUserText(event.branchEntries), ctx.sessionManager.getSessionFile());
      return { compaction: { ...result, summary, details } };
    } catch (error) {
      if (event.signal.aborted) return;
      return fallback(`${name} failed: ${error instanceof Error ? error.message : String(error)}`, error);
    } finally {
      if (ctx.hasUI) {
        ctx.ui.setStatus(STATUS_KEY, undefined);
        ctx.ui.setWidget(STATUS_KEY, undefined);
      }
    }
  });

  pi.on("session_compact", async (event, ctx) => {
    const report = pending;
    pending = undefined;
    if (!report) return;
    // A later extension may have replaced our summary; only claim the ones we wrote.
    if (report.kind === "used" && !event.fromExtension) return;
    record(report);
    if (report.kind === "fallback" && ctx.hasUI) ctx.ui.notify(`Compaction fell back to the session model: ${report.why}`, "warning");
  });

  // Pi compacts only near the window's end; thresholdPercent compacts earlier, once the agent is idle.
  pi.on("agent_end", async (_event, ctx) => {
    if (EXIT_CHILD || thresholdRun) return;
    const config = loadConfig(ctx);
    if (!config || !overThreshold(ctx.getContextUsage(), config.thresholdPercent)) return;
    thresholdRun = true;
    const startWhenIdle = (tries: number) => {
      if (!ctx.isIdle()) {
        if (tries > 0) setTimeout(() => startWhenIdle(tries - 1), 250);
        else thresholdRun = false;
        return;
      }
      ctx.compact({
        onComplete: () => { thresholdRun = false; },
        onError: () => { thresholdRun = false; },
      });
    };
    setTimeout(() => startWhenIdle(40), 0);
  });

  // On quit, compact large sessions in a detached process, so a resume days later starts small.
  pi.on("session_shutdown", async (event, ctx) => {
    // Interactive quits only: subagents, scripts and RPC clients run in other modes.
    if (EXIT_CHILD || event.reason !== "quit" || ctx.mode !== "tui") return;
    const config = loadConfig(ctx);
    const min = config?.compactOnExitMinTokens;
    const tokens = ctx.getContextUsage()?.tokens;
    const sessionFile = ctx.sessionManager.getSessionFile();
    if (!min || !tokens || tokens < min || !sessionFile || !existsSync(sessionFile)) return;
    if (ctx.sessionManager.getLeafEntry()?.type === "compaction") return;
    startExitCompaction(sessionFile, ctx);
  });

  pi.on("session_start", async (_event, ctx) => {
    const sessionFile = ctx.sessionManager.getSessionFile();
    if (ctx.hasUI && sessionFile && existsSync(`${sessionFile}.compacting`)) {
      ctx.ui.notify("This session is still being compacted in the background. Wait for it to finish before you continue, or the two writers may clash.", "warning");
    }
  });

  pi.on("session_compact_failed", async (event) => {
    const report = pending;
    pending = undefined;
    if (!report || event.aborted) return;
    record({ kind: "failed", model: report.model, reason: event.reason, sessionModel: report.sessionModel, why: event.errorMessage ?? "unknown error" });
  });

  pi.registerCommand("compact-model", {
    description: "Show which model runs compaction and whether it is ready",
    handler: async (_args, ctx) => {
      const config = loadConfig(ctx);
      if (!config) { ctx.ui.notify("Compaction uses the session model (no compactionModel setting).", "info"); return; }
      const reference = parseModelReference(config.model);
      const model = reference ? ctx.modelRegistry.find(reference.provider, reference.modelId) : undefined;
      if (!model) { ctx.ui.notify(`Compaction model ${config.model} is not available; Pi will use the session model.`, "warning"); return; }
      const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
      const ready = auth.ok ? "ready" : `auth failed: ${"error" in auth ? auth.error : "unknown error"}`;
      ctx.ui.notify(`Compaction model: ${config.model} (${model.name || model.id}) · ${ready} · reasons: ${config.reasons.join(", ")}`, auth.ok ? "info" : "warning");
    },
  });
}

function startExitCompaction(sessionFile: string, ctx: ExtensionContext): void {
  const piCli = process.argv[1];
  if (!piCli) return;
  const log = join(getAgentDir(), "compaction-model", "exit.log");
  try {
    const child = spawn(process.execPath, [EXIT_RUNNER, piCli, sessionFile, ctx.cwd, log], {
      detached: true,
      stdio: "ignore",
      env: process.env,
    });
    child.unref();
  } catch (error) {
    warn("could not start exit compaction", error);
  }
}

export {
  COMPACTION_REASONS,
  THINKING_LEVELS,
  parseModelReference,
  resolveConfig,
  type CompactionModelConfig,
  type CompactionReason,
  type ThinkingLevel,
} from "./config.js";
export { ENTRY_TYPE, reportParts, reportRows, type CompactionReport } from "./report.js";
